server:
  port: 8080

spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          service-url: http://microservice-${rootArtifactId}:8080

  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database-${rootArtifactId}-changelog.xml

  datasource:
    url: jdbc:postgresql://postgres:5432/skillbox
    username: ${rootArtifactId}
    password: ${rootArtifactId}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: ${rootArtifactId}
    open-in-view: false
